f = open('rosalind_dna.txt', 'r')
string_file = f.read()

def translate(dna):
    RNA = []
    for letter in dna:
        if letter == "T":
            RNA.append('U')
        else: 
            RNA.append(letter)
    RNA_string = ''.join(RNA)
    return RNA_string

string = "ACGGCAATTTTGCGGACTTTGCATTGCCCGAATTCTTGTCAGATTTCCCACTAAGTAAGCATCAAAGGCTCGGGAAGATACAAAATTCCTCAGGCAACCAGGGATAGCTCCGGTCGCGGCTTGCTTAAGGGGCATTGCGCCCCGGAGCGTGCCCCAACTATACTGACACAAGGGACAGCCGAGACCACTCGCGTGCAAAATCGGTAGAACCGGCGGTCGTTTCAAAACGTCTCGACCCAGTGACCCCTGAGCCGAATCATCGCTTCCTATCGTGCAGCATGTTTTTAACCTGGCGTCTGCCGAATAGGCGATGTATAGTAATCTCATAGAGTCCGAGTTCGTTATTCTCTATAACACTCGAGACCAGTGTCAGGAGGTATTAGGATCTGATCTGCAAATGAGACTTAAGACTGTGTTGGTCAGTGTGCTGGCGGGAGCCTGTGGAATCATTAGCCGGGGCCTACTTCGGGGATCACCTGTGTTGGCGATTGCGTGGCGCCCACTTAAACTGGATAACAAGTAGGCTAGAGTACCCTGGAGATGAACGACTGTTGTCTCCACGAAGAACGAAAGCATTATGTGTAGAGTCCGCAAGCCTCCCAACTTCCTCGCATATGTTACCTGCGTCGAGGACTGCAACGGCTGTATCGTAGGTGGGTGCGAGGCCGACCTGGCGATGGGGGACTTCTATACCTTTTCCTTCTAAGCTAACCGAGATTGAGAAGCGTCATGCCTCCCGAGATCGAAGGACAATAGTCTCCGCCGATTAGCCTAATCTGTCCTATCAGGCGGGACTCATGCGCGCTATATTCTGATGGTGTATAGCCTCATGAAGCAATAGGTACCCCTAACGGCTAAAACTAATTCACCGCAGCATCGCTTACCCCTCCGAGTATGGGAGCTGGCCCCGCCTTTCCTCGAAGTCTCTAAAAGTGGCA"

print(translate(string))
print(translate(string_file))
