f = open('rosalind_dna.txt', 'r')
string_file = f.read()

def count(string_dna):
    A = 0
    C = 0
    G = 0
    T = 0
    for letter in string_dna:
        if letter == 'A':
            A += 1
        elif letter == 'C':
            C += 1
        elif letter == 'G':
            G += 1
        elif letter == 'T':
            T += 1
        
    return A, C, G, T

   
string = 'CTAAGTCGTATGTTTGCGTAACCCCTTTGGCAGTGTGACCCTGGGGAAGAAAGATGGGCGAAATTATGGCGGAAGCTGCCCGCATAGAAACTGACCATCGCGCGCGGCTCCGTACCGGTACCATCCCGCGTCCGGGTGTGTGAGTCCGGATCACAAATTTGAGAACTTGACATGCGATGTTGGTAAGATTCCTAGTGGGCCTTATACAAGCGTCCTAGAATCGTTGCTTCCGCTCAGCCAGAGAGAGTACTGAATGGCTTTCTTACTCGCTGGAAAAGACCCCGACTAATAAGCAAGGGCGGCCACAGTGGAGGACGTACCTTAACAATTCCTCTACGGTCCTGGCTGACTAAGTGTGAAGGTATGTCCGAAACGGAGGTAGTGCTGAATACTGTGTGAGACGGCGCGGCAAGTCTCCTACGAGACATCCGTTCAGCTCCCTAGACAGGTCTTCGATGATTGCCGAGTGTCCACTCCGCGTGAGTGTCGGACTATGATCCAGTGCTGGAACAGTGAATATGGATATATGTTGGGTCCATCTTTCATAAGAAGCGCTCCTGGCCCATAATTGGAAGTAACTTCACACGGTCGCAGAGAGTCGACACTAGGACGTCAAAGGATACACATGACATTTCTGGCCACCAGCCACGCAATTCTCTAACGTTGCTTTGTGTCGAGACGGAAGACCAGTTTACTGATAACACACGCCCGGATGAACTTTCACTTCACCTACGCCGGGCAGACGGGGGTGTATCTACGTCATTAAAGGGGAGTGGGGGGTCCAAGTTAATTTGCGTATATAAACCCCGAATTTACACTTCACCGCAAAAATTTTTAAAATTGTGTGTAGGGGGAGGACTTCATCCAAGCAGGGACCATCG'

print(count(string))
print(count(string_file))